# Keeping the inline docs for the options that I use as there isn't
# a json schema for marksman yet ...

[core]
# When set to true, level 1 headings will be treated as document titles
# (this includes an assumption of having a single title in the document).
# Setting this to false automatically changes the default wiki link 
# completion style to a file-based one.
title_from_heading = false

[completion]
# The style of wiki links completion.
# Other values include: 
# * "file-stem" to complete using file name without an extension,
# * "file-path-stem" same as above but using file path.
wiki.style = "file-path-stem"
